### ISSUE TITLE
Other ideas for 18f.github.io

### ISSUE THREAD

**Issue by gbinal** [18F/18f.github.io#15]
I'm fine with leaving 18f.github.io as is, but other ideas to simplify our web presence could be: 
* redirect 18f.github.io to 18f.gsa.gov/dashboard
* redirect 18f.github.io to 18f.gsa.gov/developer
* redirect 18f.github.io to 18f.gsa.gov

**Comment by gbinal** [comment]
Restarting this conversation with @blacktm and @mbland

**Comment by gbinal** [comment]
New idea - I think that 18f.github.io could be a great alt means to find 18F content.  Kind of like a site index page except more like a team index page.  

Namely: 
* list of 18f (micro)sites
* list of shipped products 
* list of guides 
* list of case studies
* what else?  

All these lists should come from hub data

**Comment by gboone** [comment]
Could be interesting to migrate our microsites here instead of creating a
whole new repo to host another single page site.

On Thu, Mar 19, 2015 at 5:44 PM, Gray Brooks <notifications@github.com>
wrote:

> New idea - I think that 18f.github.io could be a great alt means to find
> 18F content. Kind of like a site index page except more like a team index
> page.
>
> Namely:
>
>    - list of 18f (micro)sites
>    - list of shipped products
>    - list of guides
>    - list of case studies
>    - what else?
>
> All these lists should come from hub data
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/18f.github.io/issues/15#issuecomment-83771288>.
>



-- 
Greg Boone, 18F

**Comment by gbinal** [comment]
Good point.  I'd say a good half of the microsites aren't standing on top of a repo of related resources, so it'd be all the same to them.  

Someone could step up and declare an interim standard template and any microsites that don't need their own repos could migrate over easily.

**Comment by gbinal** [comment]
Picking this thread back up, it may be worth transitioning from the current theme [out of an abundance of respect for the shopify folks](https://github.com/18F/open-source-policy/issues/37).

**Comment by gboone** [comment]
I'm not convinced it's even worth keeping this repo open now that we have 18F/dashboard. I definitely don't have time to build a second dashboard or any more products than that ones I'm already involved in.

**Comment by blacktm** [comment]
Yea, I agree with @gboone on this one, especially now that we have 18f-pages.

**Comment by gboone** [comment]
Alright, folks, all the attention this repo got this week got me thinking: 

* We're not using this repo.
* We have no intention to develop it as it is any further. 
* We have a replacement and enhancement over this with Dashboard

I don't see any reason to keep this around and think we should give ourselves until the end of the week to come up with a use for this repo otherwise we sunset it and turn off it's github pages.

**Comment by seanherron** [comment]
+1 @gboone. We shouldn't be launching sites on github.io domains anyway. Why not just make this a redirect to either 18f.gsa.gov or the dashboard? Unless we have a compelling reason to keep it up let's cut down on some of the sprawl :)

**Comment by gboone** [comment]
Meant to tag @leahbannon in the comment above. Since this was her project, want to be sure she's in on any decision to sunset it.

**Comment by gbinal** [comment]
I'm def. not for actively developing it, but do folks not find it valuable to have 18f.github.io resolve (or redirect).  For me, that's been a common place I look when beginning to check out a team's github activity.

**Comment by gbinal** [comment]
The three ideas I kicked off this issue thread with would each seem to me simple and positive.  I'm happy to do this afternoon.

**Comment by elainekamlley** [comment]
I vote to sunset or redirect to dashboard. After comparing this to our list of repos on github.com/18f and 18f.gsa.gov/dashboard, I'm not clear as to what meaningful info this site provides that isn't already said.

**Comment by NoahKunin** [comment]
Ok, seems like there's a gap of Product Ownership here per @leahbannon tagging out via Slack, which by default resets to me as the delegated authorizing official. I'll make the decision on this one. I concur with @elainekamlley and others the redirect to our dashboard makes the most functional sense, as that provides value added information over the data presented usually at https://github.com/18F/. 

@gbinal you game to hit the redirect?

**Comment by gbinal** [comment]
sure thing.

**Comment by gbinal** [comment]
https://github.com/18F/18f.github.io/pull/20 will wrap this up.  I'm waiting to merge while asking a few folks some technical questions, so I can learn how best to do this for other microsites.

**Comment by gbinal** [comment]
This is done.  18f.github.io now redirects to 18f.gsa.gov/dashboard.
