### ISSUE TITLE
Proposed to description of repo to be more descriptive.

### ISSUE THREAD

**Issue by melodykramer** [18F/18f.github.io#21]
Hey!

I'm doing a quick audit of all of 18F's GitHub repos to make sure that descriptions, ReadMe's, and issues are written as concisely and descriptively as they can be. This will help other organizations who would like to adapt our code as well as the public — who may be interested in adapting our code or contributing to our repos.

**The current title of this repo is:** GitHub pages repository

**Would it be possible to change it to:** This is 18F's GitHub pages repository, which redirects to 18F.github.io.

That way, anyone who comes across it [here](https://github.com/18F) or on GovCode will know exactly what the repo contains.

Thank you! Your ReadME looks great!

**Comment by afeld** [comment]
Updated!
